// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwrxhZUOyjHXs8Vipc2GF7u8SgUuTCths',
    appId: '1:28234906038:web:41d9e712d45c57a517e917',
    messagingSenderId: '28234906038',
    projectId: 'file-64c16',
    authDomain: 'file-64c16.firebaseapp.com',
    storageBucket: 'file-64c16.appspot.com',
    measurementId: 'G-QN1J4MXVYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRyj7up7zBAjpX6byXMMcAIbhbopiK-YI',
    appId: '1:28234906038:android:311e08075a997af017e917',
    messagingSenderId: '28234906038',
    projectId: 'file-64c16',
    storageBucket: 'file-64c16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClNJgKkn-RYKvvUpikv4DRuhdvYGuvhm4',
    appId: '1:28234906038:ios:f990c45b542f9a0f17e917',
    messagingSenderId: '28234906038',
    projectId: 'file-64c16',
    storageBucket: 'file-64c16.appspot.com',
    iosClientId: '28234906038-qkcb59tq5eunsdbj729ii102mh6cp37d.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClNJgKkn-RYKvvUpikv4DRuhdvYGuvhm4',
    appId: '1:28234906038:ios:f990c45b542f9a0f17e917',
    messagingSenderId: '28234906038',
    projectId: 'file-64c16',
    storageBucket: 'file-64c16.appspot.com',
    iosClientId: '28234906038-qkcb59tq5eunsdbj729ii102mh6cp37d.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
